name: Haskell Coverage

on:
  pull_request:
  workflow_dispatch:

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-25.05

      - name: Setup dev shell
        run: nix develop --command echo "Nix develop environment loaded"

      - name: Run tests with coverage
        run: nix develop --command cabal test --enable-coverage

      - name: Generate Codecov artifact
        run: |
          mkdir -p coverage
          nix develop --command \
            hpc-codecov cabal:lisp-interpreter-test > coverage/codecov.json

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: coverage/codecov.json
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
